In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import cross_val_score, RandomizedSearchCV, GridSearchCV, cross_validate, RepeatedKFold
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error, median_absolute_error
from matplotlib.pyplot import figure
from sklearn.model_selection import train_test_split
from sklearn.model_selection import RepeatedKFold
from sklearn.tree import plot_tree
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score, log_loss
from sklearn.model_selection import cross_val_predict
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report 

# Dataset generation

## Test

### Mild Dementia

In [2]:
import glob
from PIL import Image
import numpy as np

result = []
counter = 0
    
for k in glob.glob(r'C:\Users\italo\OneDrive\Desktop\alzheimer\Alzheimer_s Dataset\test\MildDemented\*.jpg'):
    im = Image.open(k)
    im = im.reduce(2)
    pixels = im.getdata()  
    for pixel in pixels:
        counter += 1
        if type(pixel) == int:
            pixel = (pixel,pixel,pixel)
    #result.append(pixel[1])
            result.append(int((pixel[0]+pixel[1]+pixel[2])/3))

#print(result[:9160])
print(len(result))
            #result.append(pixel[1])
#print(result[0:400])
#print(len(result)) #1638208 = 9152*179
test_mild_array = np.array(result)  
test_mild_array = test_mild_array.reshape((179, 9152)) #vedi bene QUESTO
#mask = (a > 0)
#print(test_mild_array)
#print(test_mild_array[0])
#extract_from_a = test_mild_array[0][mask] # or,  a[a%3==0]
#print(extract_from_a)
#test_mild_array.shape
#test_mild_array = pd.DataFrame(test_mild_array)
csv_test_mild = r'C:\Users\italo\OneDrive\Desktop\csv_test_mild.csv' 
#test_mild_array.to_csv(r'C:\Users\italo\OneDrive\Desktop\prova.csv
np.savetxt(csv_test_mild, test_mild_array, fmt="%d", delimiter=",") 

1638208


### Moderate Dementia

In [3]:
result = []
counter = 0
    
for k in glob.glob(r'C:\Users\italo\OneDrive\Desktop\alzheimer\Alzheimer_s Dataset\test\ModerateDemented\*.jpg'):
    im = Image.open(k)
    im = im.reduce(2)
    pixels = im.getdata()  
    for pixel in pixels:
        counter += 1
        if type(pixel) == int:
            pixel = (pixel,pixel,pixel)
            result.append(int((pixel[0]+pixel[1]+pixel[2])/3))
            
test_moderate_array = np.array(result)
test_moderate_array = test_moderate_array.reshape((12, 9152)) 
csv_test_moderate = r'C:\Users\italo\OneDrive\Desktop\csv_test_moderate.csv'
np.savetxt(csv_test_moderate, test_moderate_array, fmt="%d", delimiter=",")

### Non Dementia

In [4]:
result = []
counter = 0
    
for k in glob.glob(r'C:\Users\italo\OneDrive\Desktop\alzheimer\Alzheimer_s Dataset\test\NonDemented\*.jpg'):
    im = Image.open(k)
    im = im.reduce(2)
    pixels = im.getdata()  
    for pixel in pixels:
        counter += 1
        if type(pixel) == int:
            pixel = (pixel,pixel,pixel)
            result.append(int((pixel[0]+pixel[1]+pixel[2])/3))
            
test_non_array = np.array(result)
test_non_array = test_non_array.reshape((640, 9152)) 
csv_test_non = r'C:\Users\italo\OneDrive\Desktop\csv_test_non.csv'
np.savetxt(csv_test_non, test_non_array, fmt="%d", delimiter=",")

### Very Mild Dementia

In [5]:
result = []
counter = 0
    
for k in glob.glob(r'C:\Users\italo\OneDrive\Desktop\alzheimer\Alzheimer_s Dataset\test\VeryMildDemented\*.jpg'):
    im = Image.open(k)
    im = im.reduce(2)
    pixels = im.getdata()  
    for pixel in pixels:
        counter += 1
        if type(pixel) == int:
            pixel = (pixel,pixel,pixel)
            result.append(int((pixel[0]+pixel[1]+pixel[2])/3))
            
test_very_array = np.array(result)
test_very_array = test_very_array.reshape((448, 9152)) 
csv_test_very = r'C:\Users\italo\OneDrive\Desktop\csv_test_very.csv'
np.savetxt(csv_test_very, test_very_array, fmt="%d", delimiter=",")

## Train

### Mild Dementia

In [6]:
result = []
counter = 0
    
for k in glob.glob(r'C:\Users\italo\OneDrive\Desktop\alzheimer\Alzheimer_s Dataset\train\MildDemented\*.jpg'):
    im = Image.open(k)
    im = im.reduce(2)
    pixels = im.getdata()  
    for pixel in pixels:
        counter += 1
        if type(pixel) == int:
            pixel = (pixel,pixel,pixel)
            result.append(int((pixel[0]+pixel[1]+pixel[2])/3))
            
train_mild_array = np.array(result)
train_mild_array = train_mild_array.reshape((717, 9152)) 
csv_train_mild = r'C:\Users\italo\OneDrive\Desktop\csv_train_mild.csv'
np.savetxt(csv_train_mild, train_mild_array, fmt="%d", delimiter=",")

### Moderate Dementia

In [7]:
result = []
counter = 0
    
for k in glob.glob(r'C:\Users\italo\OneDrive\Desktop\alzheimer\Alzheimer_s Dataset\train\ModerateDemented\*.jpg'):
    im = Image.open(k)
    im = im.reduce(2)
    pixels = im.getdata()  
    for pixel in pixels:
        counter += 1
        if type(pixel) == int:
            pixel = (pixel,pixel,pixel)
            result.append(int((pixel[0]+pixel[1]+pixel[2])/3))
            
train_moderate_array = np.array(result)
train_moderate_array = train_moderate_array.reshape((52, 9152)) 
csv_train_moderate = r'C:\Users\italo\OneDrive\Desktop\csv_train_moderate.csv'
np.savetxt(csv_train_moderate, train_moderate_array, fmt="%d", delimiter=",")

### Non Dementia

In [8]:
result = []
counter = 0
    
for k in glob.glob(r'C:\Users\italo\OneDrive\Desktop\alzheimer\Alzheimer_s Dataset\train\NonDemented\*.jpg'):
    im = Image.open(k)
    im = im.reduce(2)
    pixels = im.getdata()  
    for pixel in pixels:
        counter += 1
        if type(pixel) == int:
            pixel = (pixel,pixel,pixel)
            result.append(int((pixel[0]+pixel[1]+pixel[2])/3))
            
train_non_array = np.array(result)
train_non_array = train_non_array.reshape((2560, 9152)) 
csv_train_non = r'C:\Users\italo\OneDrive\Desktop\csv_train_non.csv'
np.savetxt(csv_train_non, train_non_array, fmt="%d", delimiter=",")

### Very Mild Dementia

In [9]:
result = []
counter = 0
    
for k in glob.glob(r'C:\Users\italo\OneDrive\Desktop\alzheimer\Alzheimer_s Dataset\train\VeryMildDemented\*.jpg'):
    im = Image.open(k)
    im = im.reduce(2)
    pixels = im.getdata()  
    for pixel in pixels:
        counter += 1
        if type(pixel) == int:
            pixel = (pixel,pixel,pixel)
            result.append(int((pixel[0]+pixel[1]+pixel[2])/3))
            
train_very_array = np.array(result)
train_very_array = train_very_array.reshape((1792, 9152)) 
csv_train_very = r'C:\Users\italo\OneDrive\Desktop\csv_train_very.csv'
np.savetxt(csv_train_very, train_very_array, fmt="%d", delimiter=",")

In [10]:
#code for a single image
#import pandas as pd
#im = Image.open(r'C:\Users\italo\OneDrive\Desktop\lena.jpg')
#im = im.reduce(2)
#pixels = im.getdata()
#result = []
#counter = 0
#for pixel in pixels:
    #counter += 1
    #if type(pixel) == int:
        #pixel = (pixel,pixel,pixel)
    #result.append(pixel[1])
    #result.append(pixel[1])

## adding variable 'label' 

In [10]:
import pandas as pd

### test - non

In [11]:
directory = r'C:\Users\italo\OneDrive\Desktop'
file = 'csv_test_non.csv'
df_test_non = pd.read_csv(f'{directory}/{file}')

In [12]:
non_label = np.array([0 for i in range (639)]) #we create a an array with all 0
non_label = non_label.T #transposes array
#non_label.shape
non_label = pd.DataFrame(non_label) #transforms in a pandas object to me concateneted with this library

In [13]:
non_labelized_test = pd.concat([df_test_non, non_label], axis=1) #concats per column
non_labelized_test.rename(columns = {non_labelized_test.columns[-1]:'label'}) #renames last variable

0  0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  0.9  ...  0.4225  0.4226  \
0    0    0    0    0    0    0    0    0    0    0  ...       0       0   
1    0    0    0    0    0    0    0    0    0    0  ...       0       0   
2    0    0    0    0    0    0    0    0    0    0  ...       0       0   
3    0    0    0    0    0    0    0    0    0    0  ...       0       0   
4    0    0    0    0    0    0    0    0    0    0  ...       0       0   
..  ..  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...     ...     ...   
634  0    0    0    0    0    0    0    0    0    0  ...       0       0   
635  0    0    0    0    0    0    0    0    0    0  ...       0       0   
636  0    0    0    0    0    0    0    0    0    0  ...       0       0   
637  0    0    0    0    0    0    0    0    0    0  ...       0       0   
638  0    0    0    0    0    0    0    0    0    0  ...       0       0   

     0.4227  0.4228  0.4229  0.4230  0.4231  0.4232  0.4233  label  
0         0       0       0       0       0       0       0      0  
1         0       0       0       0       0       0       0      0  
2         0       0       0       0       0       0       0      0  
3         0       0       0       0       0       0       0      0  
4         0       0       0       0       0       0       0      0  
..      ...     ...     ...     ...     ...     ...     ...    ...  
634       0       0       0       0       0       0       0      0  
635       0       0       0       0       0       0       0      0  
636       0       0       0       0       0       0       0      0  
637       0       0       0       0       0       0       0      0  
638       0       0       0       0       0       0       0      0  

[639 rows x 9153 columns]

### test - very

In [14]:
directory = r'C:\Users\italo\OneDrive\Desktop'
file = 'csv_test_very.csv'
df_test_very = pd.read_csv(f'{directory}/{file}')
very_label = np.array([1 for i in range (447)])
very_label = very_label.T
very_label = pd.DataFrame(very_label)
very_labelized_test = pd.concat([df_test_very, very_label], axis=1)
very_labelized_test.rename(columns = {very_labelized_test.columns[-1]:'label'})

0  0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  0.9  ...  0.4217  0.4218  \
0    0    0    0    0    0    0    0    0    0    0  ...       0       0   
1    0    0    0    0    0    0    0    0    0    0  ...       0       0   
2    0    0    0    0    0    0    0    0    0    0  ...       0       0   
3    0    0    0    0    0    0    0    0    0    0  ...       0       0   
4    0    0    0    0    0    0    0    0    0    0  ...       0       0   
..  ..  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...     ...     ...   
442  0    0    0    0    0    0    0    0    0    0  ...       0       0   
443  0    0    0    0    0    0    0    0    0    0  ...       0       0   
444  0    0    0    0    0    0    0    0    0    0  ...       0       0   
445  0    0    0    0    0    0    0    0    0    0  ...       0       0   
446  0    0    0    0    0    0    0    0    0    0  ...       0       0   

     0.4219  0.4220  0.4221  0.4222  0.4223  0.4224  0.4225  label  
0         0       0       0       0       0       0       0      1  
1         0       0       0       0       0       0       0      1  
2         0       0       0       0       0       0       0      1  
3         0       0       0       0       0       0       0      1  
4         0       0       0       0       0       0       0      1  
..      ...     ...     ...     ...     ...     ...     ...    ...  
442       0       0       0       0       0       0       0      1  
443       0       0       0       0       0       0       0      1  
444       0       0       0       0       0       0       0      1  
445       0       0       0       0       0       0       0      1  
446       0       0       0       0       0       0       0      1  

[447 rows x 9153 columns]

### test - mild

In [15]:
directory = r'C:\Users\italo\OneDrive\Desktop'
file = 'csv_test_mild.csv'
df_test_mild = pd.read_csv(f'{directory}/{file}')
mild_label = np.array([2 for i in range (178)])
mild_label = mild_label.T
mild_label = pd.DataFrame(mild_label)
mild_labelized_test = pd.concat([df_test_mild, mild_label], axis=1)
mild_labelized_test.rename(columns = {mild_labelized_test.columns[-1]:'label'})

0  0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  0.9  ...  0.4211  0.4212  \
0    0    0    0    0    0    0    0    0    0    0  ...       0       0   
1    0    0    0    0    0    0    0    0    0    0  ...       0       0   
2    0    0    0    0    0    0    0    0    0    0  ...       0       0   
3    0    0    0    0    0    0    0    0    0    0  ...       0       0   
4    0    0    0    0    0    0    0    0    0    0  ...       0       0   
..  ..  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...     ...     ...   
173  0    0    0    0    0    0    0    0    0    0  ...       0       0   
174  0    0    0    0    0    0    0    0    0    0  ...       0       0   
175  0    0    0    0    0    0    0    0    0    0  ...       0       0   
176  0    0    0    0    0    0    0    0    0    0  ...       0       0   
177  0    0    0    0    0    0    0    0    0    0  ...       0       0   

     0.4213  0.4214  0.4215  0.4216  0.4217  0.4218  0.4219  label  
0         0       0       0       0       0       0       0      2  
1         0       0       0       0       0       0       0      2  
2         0       0       0       0       0       0       0      2  
3         0       0       0       0       0       0       0      2  
4         0       0       0       0       0       0       0      2  
..      ...     ...     ...     ...     ...     ...     ...    ...  
173       0       0       0       0       0       0       0      2  
174       0       0       0       0       0       0       0      2  
175       0       0       0       0       0       0       0      2  
176       0       0       0       0       0       0       0      2  
177       0       0       0       0       0       0       0      2  

[178 rows x 9153 columns]

### test - moderate

In [16]:
directory = r'C:\Users\italo\OneDrive\Desktop'
file = 'csv_test_moderate.csv'
df_test_moderate = pd.read_csv(f'{directory}/{file}')
moderate_label = np.array([3 for i in range (11)])
moderate_label = moderate_label.T
moderate_label = pd.DataFrame(moderate_label)
moderate_labelized_test = pd.concat([df_test_moderate, moderate_label], axis=1)
moderate_labelized_test.rename(columns = {moderate_labelized_test.columns[-1]:'label'})

0  0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  0.9  ...  0.4218  0.4219  \
0   0    0    0    0    0    0    0    0    0    0  ...       0       0   
1   0    0    0    0    0    0    0    0    0    0  ...       0       0   
2   0    0    0    0    0    0    0    0    0    0  ...       0       0   
3   0    0    0    0    0    0    0    0    0    0  ...       0       0   
4   0    0    0    0    0    0    0    0    0    0  ...       0       0   
5   0    0    0    0    0    0    0    0    0    0  ...       0       0   
6   0    0    0    0    0    0    0    0    0    0  ...       0       0   
7   0    0    0    0    0    0    0    0    0    0  ...       0       0   
8   0    0    0    0    0    0    0    0    0    0  ...       0       0   
9   0    0    0    0    0    0    0    0    0    0  ...       0       0   
10  0    0    0    0    0    0    0    0    0    0  ...       0       0   

    0.4220  0.4221  0.4222  0.4223  0.4224  0.4225  0.4226  label  
0        0       0       0       0       0       0       0      3  
1        0       0       0       0       0       0       0      3  
2        0       0       0       0       0       0       0      3  
3        0       0       0       0       0       0       0      3  
4        0       0       0       0       0       0       0      3  
5        0       0       0       0       0       0       0      3  
6        0       0       0       0       0       0       0      3  
7        0       0       0       0       0       0       0      3  
8        0       0       0       0       0       0       0      3  
9        0       0       0       0       0       0       0      3  
10       0       0       0       0       0       0       0      3  

[11 rows x 9153 columns]

### train - non

In [17]:
directory = r'C:\Users\italo\OneDrive\Desktop'
file = 'csv_train_non.csv'
df_test_non = pd.read_csv(f'{directory}/{file}')
non_label = np.array([0 for i in range (2559)])
non_label = non_label.T
non_label = pd.DataFrame(non_label)
non_labelized_train = pd.concat([df_test_non, non_label], axis=1)
non_labelized_train.rename(columns = {non_labelized_train.columns[-1]:'label'})

0  0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  0.9  ...  0.4016  0.4017  \
0     0    0    0    0    0    0    0    0    0    0  ...       0       0   
1     0    0    0    0    0    0    0    0    0    0  ...       0       0   
2     0    0    0    0    0    0    0    0    0    0  ...       0       0   
3     0    0    0    0    0    0    0    0    0    0  ...       0       0   
4     0    0    0    0    0    0    0    0    0    0  ...       0       0   
...  ..  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...     ...     ...   
2554  0    0    0    0    0    0    0    0    0    0  ...       0       0   
2555  0    0    0    0    0    0    0    0    0    0  ...       0       0   
2556  0    0    0    0    0    0    0    0    0    0  ...       0       0   
2557  0    0    0    0    0    0    0    0    0    0  ...       0       0   
2558  0    0    0    0    0    0    0    0    0    0  ...       0       0   

      0.4018  0.4019  0.4020  0.4021  0.4022  0.4023  0.4024  label  
0          0       0       0       0       0       0       0      0  
1          0       0       0       0       0       0       0      0  
2          0       0       0       0       0       0       0      0  
3          0       0       0       0       0       0       0      0  
4          0       0       0       0       0       0       0      0  
...      ...     ...     ...     ...     ...     ...     ...    ...  
2554       0       0       0       0       0       0       0      0  
2555       0       0       0       0       0       0       0      0  
2556       0       0       0       0       0       0       0      0  
2557       0       0       0       0       0       0       0      0  
2558       0       0       0       0       0       0       0      0  

[2559 rows x 9153 columns]

### train - very

In [18]:
directory = r'C:\Users\italo\OneDrive\Desktop'
file = 'csv_train_very.csv'
df_test_very = pd.read_csv(f'{directory}/{file}')
very_label = np.array([1 for i in range (1791)])
very_label = very_label.T
very_label = pd.DataFrame(very_label)
very_labelized_train = pd.concat([df_test_very, very_label], axis=1)
very_labelized_train.rename(columns = {very_labelized_train.columns[-1]:'label'})

0  0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  0.9  ...  0.4033  0.4034  \
0     0    0    0    0    0    0    0    0    0    0  ...       0       0   
1     0    0    0    0    0    0    0    0    0    0  ...       0       0   
2     0    0    0    0    0    0    0    0    0    0  ...       0       0   
3     0    0    0    0    0    0    0    0    0    0  ...       0       0   
4     0    0    0    0    0    0    0    0    0    0  ...       0       0   
...  ..  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...     ...     ...   
1786  0    0    0    0    0    0    0    0    0    0  ...       0       0   
1787  0    0    0    0    0    0    0    0    0    0  ...       0       0   
1788  0    0    0    0    0    0    0    0    0    0  ...       0       0   
1789  0    0    0    0    0    0    0    0    0    0  ...       0       0   
1790  0    0    0    0    0    0    0    0    0    0  ...       0       0   

      0.4035  0.4036  0.4037  0.4038  0.4039  0.4040  0.4041  label  
0          0       0       0       0       0       0       0      1  
1          0       0       0       0       0       0       0      1  
2          0       0       0       0       0       0       0      1  
3          0       0       0       0       0       0       0      1  
4          0       0       0       0       0       0       0      1  
...      ...     ...     ...     ...     ...     ...     ...    ...  
1786       0       0       0       0       0       0       0      1  
1787       0       0       0       0       0       0       0      1  
1788       0       0       0       0       0       0       0      1  
1789       0       0       0       0       0       0       0      1  
1790       0       0       0       0       0       0       0      1  

[1791 rows x 9153 columns]

### train - mild

In [19]:
directory = r'C:\Users\italo\OneDrive\Desktop'
file = 'csv_train_mild.csv'
df_test_mild = pd.read_csv(f'{directory}/{file}')
mild_label = np.array([2 for i in range (716)])
mild_label = mild_label.T
mild_label = pd.DataFrame(mild_label)
mild_labelized_train = pd.concat([df_test_mild, mild_label], axis=1)
mild_labelized_train.rename(columns = {mild_labelized_train.columns[-1]:'label'})

0  0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  0.9  ...  0.4055  0.4056  \
0    0    0    0    0    0    0    0    0    0    0  ...       0       0   
1    0    0    0    0    0    0    0    0    0    0  ...       0       0   
2    0    0    0    0    0    0    0    0    0    0  ...       0       0   
3    0    0    0    0    0    0    0    0    0    0  ...       0       0   
4    0    0    0    0    0    0    0    0    0    0  ...       0       0   
..  ..  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...     ...     ...   
711  0    0    0    0    0    0    0    0    0    0  ...       0       0   
712  0    0    0    0    0    0    0    0    0    0  ...       0       0   
713  0    0    0    0    0    0    0    0    0    0  ...       0       0   
714  0    0    0    0    0    0    0    0    0    0  ...       0       0   
715  0    0    0    0    0    0    0    0    0    0  ...       0       0   

     0.4057  0.4058  0.4059  0.4060  0.4061  0.4062  0.4063  label  
0         0       0       0       0       0       0       0      2  
1         0       0       0       0       0       0       0      2  
2         0       0       0       0       0       0       0      2  
3         0       0       0       0       0       0       0      2  
4         0       0       0       0       0       0       0      2  
..      ...     ...     ...     ...     ...     ...     ...    ...  
711       0       0       0       0       0       0       0      2  
712       0       0       0       0       0       0       0      2  
713       0       0       0       0       0       0       0      2  
714       0       0       0       0       0       0       0      2  
715       0       0       0       0       0       0       0      2  

[716 rows x 9153 columns]

### train - moderate

In [20]:
directory = r'C:\Users\italo\OneDrive\Desktop'
file = 'csv_train_moderate.csv'
df_test_moderate = pd.read_csv(f'{directory}/{file}')
moderate_label = np.array([3 for i in range (51)])
moderate_label = moderate_label.T
moderate_label = pd.DataFrame(moderate_label)
moderate_labelized_train = pd.concat([df_test_moderate, moderate_label], axis=1)
moderate_labelized_train.rename(columns = {moderate_labelized_train.columns[-1]:'label'})
moderate_labelized_train.head() #here we use head because otherwise would have printed all dataset

0  0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  0.9  ...  0.4017  0.4018  \
0  0    0    0    0    0    0    0    0    0    0  ...       0       0   
1  0    0    0    0    0    0    0    0    0    0  ...       0       0   
2  0    0    0    0    0    0    0    0    0    0  ...       0       0   
3  0    0    0    0    0    0    0    0    0    0  ...       0       0   
4  0    0    0    0    0    0    0    0    0    0  ...       0       0   

   0.4019  0.4020  0.4021  0.4022  0.4023  0.4024  0.4025  0  
0       0       0       0       0       0       0       0  3  
1       0       0       0       0       0       0       0  3  
2       0       0       0       0       0       0       0  3  
3       0       0       0       0       0       0       0  3  
4       0       0       0       0       0       0       0  3  

[5 rows x 9153 columns]

## Merging dfs

In [21]:
a = np.array(non_labelized_test)
e = np.array(non_labelized_train)
non = np.concatenate((a, e), axis=0)
non = non[:1600, :]
non.shape

(1600, 9153)

In [22]:
b = np.array(very_labelized_test)
f = np.array(very_labelized_train)
very_mild = np.concatenate((b, f), axis=0)
very_mild = very_mild[:1600, :]
very_mild.shape
#print(very_mild)

(1600, 9153)

In [23]:
c = np.array(mild_labelized_test)
g = np.array(mild_labelized_train)
mild = np.concatenate((c, g), axis = 0)
mild = np.concatenate((mild, mild), axis = 0) 
mild = mild[:1600, :]
mild.shape
#print(mild)

(1600, 9153)

In [24]:
d = np.array(moderate_labelized_test)
h = np.array(moderate_labelized_train)
moderate = np.concatenate((d, h), axis = 0)
moderate = np.concatenate((moderate,moderate,moderate,moderate,moderate,moderate,moderate,moderate,moderate,moderate,moderate,moderate,moderate,moderate,moderate,moderate,moderate,moderate,moderate,moderate,moderate,moderate,moderate,moderate,moderate,moderate,moderate,), axis = 0) 
moderate = moderate[:1600, :]
print(moderate.shape)


(1600, 9153)


In [25]:
#use numpy to concatenate dataframes in one
array = np.concatenate((non, very_mild, mild, moderate), axis = 0) #concatenates per row
#array.shape

In [26]:
#use numpy to save these data in csv format
path = r'C:\Users\italo\OneDrive\Desktop\PIXEL\Reduce_2\table.csv'
np.savetxt(path, array, fmt="%d", delimiter=",")

In [28]:
directory = r'C:\Users\italo\OneDrive\Desktop\PIXEL\Reduce_2'
file = 'table.csv'
df = pd.read_csv(f'{directory}/{file}')

In [29]:
df[df.columns[-1]] = df[df.columns[-1]].apply(lambda x: float(x))

In [30]:
X = df.loc[:, df.columns != df.columns[-1]].values
y = df.loc[:, df.columns == df.columns[-1]].values
y = y.ravel()
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

In [31]:
y.shape

(6399,)

In [32]:
cv = RepeatedKFold(n_splits=10, n_repeats=3, random_state=30)

## Decision Tree Classifier 

In [33]:
# Function to perform training with giniIndex. 
def train_using_gini(X_train, X_test, y_train): 
  
    # Creating the classifier object 
    clf_gini = DecisionTreeClassifier(criterion = "gini", 
            random_state = 100,max_depth=3, min_samples_leaf=5) 
  
    # Performing training 
    clf_gini.fit(X_train, y_train) 
    return clf_gini 
      
# Function to perform training with entropy. 
def tarin_using_entropy(X_train, X_test, y_train): 
  
    # Decision tree with entropy 
    clf_entropy = DecisionTreeClassifier( 
            criterion = "entropy", random_state = 100, 
            max_depth = 3, min_samples_leaf = 5) 
  
    # Performing training 
    clf_entropy.fit(X_train, y_train) 
    return clf_entropy 

def prediction(X_test, clf_object): 
  
    # Predicton on test with giniIndex 
    y_pred = clf_object.predict(X_test) 
    print("Predicted values:") 
    print(y_pred) 
    return y_pred 
      
# Function to calculate accuracy 
def cal_accuracy(y_test, y_pred): 
      
    print("Confusion Matrix: ", 
        confusion_matrix(y_test, y_pred)) 
      
    print ("Accuracy : ", 
    accuracy_score(y_test,y_pred)*100) 
      
    print("Report : ", 
    classification_report(y_test, y_pred)) 
    
# Driver code 
def main(): 
      
    # Building Phase 
    #data = importdata() 
    #X, Y, X_train, X_test, y_train, y_test = splitdataset(data) 
    clf_gini = train_using_gini(X_train, X_test, y_train) 
    clf_entropy = tarin_using_entropy(X_train, X_test, y_train) 
      
    # Operational Phase 
    print("Results Using Gini Index:") 
      
    # Prediction using gini 
    y_pred_gini = prediction(X_test, clf_gini) 
    cal_accuracy(y_test, y_pred_gini) 
      
    print("Results Using Entropy:") 
    # Prediction using entropy 
    y_pred_entropy = prediction(X_test, clf_entropy) 
    cal_accuracy(y_test, y_pred_entropy) 
      
      # Calling main function 
if __name__=="__main__": 
    main() 

Results Using Gini Index:
Predicted values:
[3. 2. 3. ... 3. 3. 2.]
Confusion Matrix:  [[156 166 141  20]
 [ 34 162 258  27]
 [  4  57 356  51]
 [  0   0  34 454]]
Accuracy :  58.75
Report :                precision    recall  f1-score   support

         0.0       0.80      0.32      0.46       483
         1.0       0.42      0.34      0.37       481
         2.0       0.45      0.76      0.57       468
         3.0       0.82      0.93      0.87       488

    accuracy                           0.59      1920
   macro avg       0.62      0.59      0.57      1920
weighted avg       0.63      0.59      0.57      1920

Results Using Entropy:
Predicted values:
[3. 1. 3. ... 3. 3. 1.]
Confusion Matrix:  [[158 203  92  30]
 [ 31 299 112  39]
 [ 11 168 193  96]
 [  0   0   0 488]]
Accuracy :  59.27083333333333
Report :                precision    recall  f1-score   support

         0.0       0.79      0.33      0.46       483
         1.0       0.45      0.62      0.52       481
         